apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderitem-deployment
  labels:
    app: OrderItem
spec:
  replicas: 1
  selector:
    matchLabels:
        app: OrderItem
  template: 
    metadata: 
        labels: 
            app: OrderItem
    spec: 
        containers: 
        - name: cloudpracticecheckorderitem
          image: cloudpracticecheck.azurecr.io/cloudpracticecheckorderitem:latest
          ports: 
          - containerPort: 8080
        imagePullSecrets:
        - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata: 
    name: orderitemservice
spec: 
    type: LoadBalancer
    ports: 
    - port: 80
    selector:
        app : OrderItem
